/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PlanType = IDL.Variant({
  'lifetime' : IDL.Null,
  'weekly' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AdminAuditEntry = IDL.Record({
  'action' : IDL.Text,
  'admin' : IDL.Principal,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
});
export const Region = IDL.Variant({
  'usa' : IDL.Null,
  'europe' : IDL.Null,
  'brasil' : IDL.Null,
  'other' : IDL.Null,
  'asia' : IDL.Null,
  'arabia' : IDL.Null,
  'india' : IDL.Null,
  'africa' : IDL.Null,
});
export const OpenInterestMomentum = IDL.Variant({
  'steady' : IDL.Null,
  'decreasing' : IDL.Null,
  'increasing' : IDL.Null,
});
export const InstitutionalCriteria = IDL.Record({
  'hasOb' : IDL.Bool,
  'hasDisplacement' : IDL.Bool,
  'hasFvg' : IDL.Bool,
  'hasManipulation' : IDL.Bool,
  'hasInstitutionalTarget' : IDL.Bool,
  'hasMitigation' : IDL.Bool,
  'hasChoch' : IDL.Bool,
  'hasLiquidity' : IDL.Bool,
});
export const VolumeStrength = IDL.Variant({
  'low' : IDL.Null,
  'veryHigh' : IDL.Null,
  'high' : IDL.Null,
  'extreme' : IDL.Null,
  'medium' : IDL.Null,
});
export const RsiTrend = IDL.Variant({
  'steady' : IDL.Null,
  'rising' : IDL.Null,
  'falling' : IDL.Null,
});
export const EarlyConfluence = IDL.Record({
  'probability' : IDL.Float64,
  'volumeSpike' : IDL.Bool,
  'patternFormation' : IDL.Bool,
  'signalStrength' : IDL.Text,
  'projectedReversal' : IDL.Bool,
  'timingEstimate' : IDL.Float64,
  'isEarlyConfirmed' : IDL.Bool,
  'rsiMomentum' : IDL.Bool,
  'institutionalVolume' : IDL.Bool,
  'confluenceLabel' : IDL.Text,
  'confluenceScore' : IDL.Float64,
  'shortIntervalSignal' : IDL.Bool,
});
export const CryptoAsset = IDL.Record({
  'region' : Region,
  'openInterestMomentum' : OpenInterestMomentum,
  'volatility' : IDL.Float64,
  'institutionalCriteria' : InstitutionalCriteria,
  'volumeStrength' : VolumeStrength,
  'volumeMarketCapRatio' : IDL.Float64,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'percentageChange' : IDL.Float64,
  'correlation' : IDL.Float64,
  'description' : IDL.Text,
  'volume' : IDL.Float64,
  'openInterest' : IDL.Float64,
  'momentum' : IDL.Float64,
  'isInstitutionalSetup' : IDL.Bool,
  'openInterestStatus' : IDL.Text,
  'hasStrongConfluence' : IDL.Bool,
  'confluenceScore' : IDL.Float64,
  'price' : IDL.Float64,
  'rsiTrend' : RsiTrend,
  'hasConfluence' : IDL.Bool,
  'rsiValue' : IDL.Float64,
  'recommendationScore' : IDL.Float64,
  'rsiStatus' : IDL.Text,
  'symbol' : IDL.Text,
  'setupNarrative' : IDL.Text,
  'earlyConfluence' : EarlyConfluence,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Opt(IDL.Text),
});
export const FlowMetrics = IDL.Record({
  'direction' : IDL.Text,
  'volumeStrength' : IDL.Float64,
  'threshold' : IDL.Text,
  'netFlow' : IDL.Float64,
  'percentageChange' : IDL.Float64,
  'totalFlow' : IDL.Float64,
  'inflow' : IDL.Float64,
  'hasStrongConfluence' : IDL.Bool,
  'outflow' : IDL.Float64,
  'intensity' : IDL.Text,
});
export const Category = IDL.Variant({
  'btc' : IDL.Null,
  'eth' : IDL.Null,
  'altcoins' : IDL.Null,
});
export const CategoryMetrics = IDL.Record({
  'trend' : IDL.Text,
  'marketCap' : IDL.Float64,
  'name' : IDL.Text,
  'volume' : IDL.Float64,
  'flowMetrics' : FlowMetrics,
  'category' : Category,
  'price' : IDL.Float64,
});
export const Chapter = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'number' : IDL.Nat,
});
export const DominanceTrend = IDL.Variant({
  'up' : IDL.Null,
  'steady' : IDL.Null,
  'down' : IDL.Null,
});
export const DominanceData = IDL.Record({
  'btcDominance' : IDL.Float64,
  'trend' : DominanceTrend,
  'change24h' : IDL.Float64,
  'usdDominance' : IDL.Float64,
  'bitcoinCap' : IDL.Float64,
  'stablecoinCap' : IDL.Float64,
  'totalCryptoCap' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const PaymentMethod = IDL.Variant({
  'icp' : IDL.Null,
  'stripe' : IDL.Null,
  'stablecoin' : IDL.Null,
});
export const PaymentConfig = IDL.Record({
  'method' : PaymentMethod,
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
  'priceUsd' : IDL.Float64,
  'planType' : PlanType,
});
export const PaymentTransaction = IDL.Record({
  'status' : IDL.Text,
  'method' : PaymentMethod,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'updatedAt' : IDL.Opt(IDL.Int),
  'amountUsd' : IDL.Float64,
  'planType' : PlanType,
  'transactionId' : IDL.Text,
});
export const StripeConfigurationPublic = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'isConfigured' : IDL.Bool,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const SubscriptionStatus = IDL.Variant({
  'active' : IDL.Record({ 'expiresAt' : IDL.Opt(IDL.Int) }),
  'canceled' : IDL.Record({ 'canceledAt' : IDL.Opt(IDL.Int) }),
  'expired' : IDL.Record({ 'lastActive' : IDL.Opt(IDL.Int) }),
  'pending' : IDL.Record({ 'startedAt' : IDL.Opt(IDL.Int) }),
});
export const Subscription = IDL.Record({
  'status' : SubscriptionStatus,
  'createdAt' : IDL.Int,
  'user' : IDL.Principal,
  'updatedAt' : IDL.Opt(IDL.Int),
  'lastPaymentId' : IDL.Opt(IDL.Text),
  'planType' : PlanType,
});
export const TelegramPostLog = IDL.Record({
  'admin' : IDL.Principal,
  'messagePreview' : IDL.Text,
  'errorDetails' : IDL.Opt(IDL.Text),
  'httpStatusCode' : IDL.Opt(IDL.Nat),
  'timestamp' : IDL.Int,
  'success' : IDL.Bool,
});
export const TelegramPostResult = IDL.Record({
  'resultMessage' : IDL.Text,
  'messageId' : IDL.Opt(IDL.Int),
  'errorDetails' : IDL.Opt(IDL.Text),
  'httpStatusCode' : IDL.Opt(IDL.Nat),
  'isSuccess' : IDL.Bool,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'activateSubscription' : IDL.Func([PlanType, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelSubscription' : IDL.Func([], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createIcpPayment' : IDL.Func([PlanType], [IDL.Text], []),
  'createStablecoinPayment' : IDL.Func([PlanType], [IDL.Text], []),
  'getAdminAuditLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AdminAuditEntry)],
      ['query'],
    ),
  'getAssetAnalysis' : IDL.Func([IDL.Text], [IDL.Opt(CryptoAsset)], ['query']),
  'getAssetChartData' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Float64)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryMetrics' : IDL.Func([], [IDL.Vec(CategoryMetrics)], ['query']),
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
  'getDominanceAlerts' : IDL.Func(
      [IDL.Float64],
      [
        IDL.Vec(
          IDL.Record({
            'dominanceValue' : IDL.Float64,
            'message' : IDL.Text,
            'dominanceType' : IDL.Text,
            'timestamp' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getDominanceComparison' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'btcDominance' : IDL.Float64,
            'usdDominance' : IDL.Float64,
            'dominanceRatio' : IDL.Float64,
            'relativeStrength' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getDominanceData' : IDL.Func([], [IDL.Vec(DominanceData)], ['query']),
  'getIntelligentRecommendations' : IDL.Func(
      [],
      [IDL.Vec(CryptoAsset)],
      ['query'],
    ),
  'getLatestDominanceMetrics' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'btcDominance' : IDL.Float64,
            'usdDominance' : IDL.Float64,
            'bitcoinCap' : IDL.Float64,
            'stablecoinCap' : IDL.Float64,
            'totalCryptoCap' : IDL.Float64,
            'timestamp' : IDL.Int,
          })
        ),
      ],
      ['query'],
    ),
  'getPaymentConfiguration' : IDL.Func(
      [PaymentMethod, PlanType],
      [IDL.Opt(PaymentConfig)],
      ['query'],
    ),
  'getPaymentTransaction' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PaymentTransaction)],
      ['query'],
    ),
  'getStripeConfiguration' : IDL.Func(
      [],
      [StripeConfigurationPublic],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getTelegramPostLog' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TelegramPostLog)],
      ['query'],
    ),
  'getThreeMinuteTimeframe' : IDL.Func([], [IDL.Text], ['query']),
  'getTopCapitalFlowProportionalToMarketCap' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Vec(
          IDL.Record({
            'usdInflow' : IDL.Float64,
            'marketCap' : IDL.Float64,
            'proportionalFlow' : IDL.Float64,
            'symbol' : IDL.Text,
          })
        ),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSubscription' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Subscription)],
      ['query'],
    ),
  'hasPremiumAccess' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'listChapters' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'title' : IDL.Text, 'number' : IDL.Nat }))],
      ['query'],
    ),
  'listPaymentConfigurations' : IDL.Func(
      [],
      [IDL.Vec(PaymentConfig)],
      ['query'],
    ),
  'listPaymentTransactions' : IDL.Func(
      [],
      [IDL.Vec(PaymentTransaction)],
      ['query'],
    ),
  'ping' : IDL.Func([], [IDL.Text], []),
  'recordPaymentTransaction' : IDL.Func([PaymentTransaction], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
  'sendTelegramPost' : IDL.Func([IDL.Text], [TelegramPostResult], []),
  'setPaymentConfiguration' : IDL.Func([PaymentConfig], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateSubscription' : IDL.Func([Subscription], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PlanType = IDL.Variant({ 'lifetime' : IDL.Null, 'weekly' : IDL.Null });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AdminAuditEntry = IDL.Record({
    'action' : IDL.Text,
    'admin' : IDL.Principal,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
  });
  const Region = IDL.Variant({
    'usa' : IDL.Null,
    'europe' : IDL.Null,
    'brasil' : IDL.Null,
    'other' : IDL.Null,
    'asia' : IDL.Null,
    'arabia' : IDL.Null,
    'india' : IDL.Null,
    'africa' : IDL.Null,
  });
  const OpenInterestMomentum = IDL.Variant({
    'steady' : IDL.Null,
    'decreasing' : IDL.Null,
    'increasing' : IDL.Null,
  });
  const InstitutionalCriteria = IDL.Record({
    'hasOb' : IDL.Bool,
    'hasDisplacement' : IDL.Bool,
    'hasFvg' : IDL.Bool,
    'hasManipulation' : IDL.Bool,
    'hasInstitutionalTarget' : IDL.Bool,
    'hasMitigation' : IDL.Bool,
    'hasChoch' : IDL.Bool,
    'hasLiquidity' : IDL.Bool,
  });
  const VolumeStrength = IDL.Variant({
    'low' : IDL.Null,
    'veryHigh' : IDL.Null,
    'high' : IDL.Null,
    'extreme' : IDL.Null,
    'medium' : IDL.Null,
  });
  const RsiTrend = IDL.Variant({
    'steady' : IDL.Null,
    'rising' : IDL.Null,
    'falling' : IDL.Null,
  });
  const EarlyConfluence = IDL.Record({
    'probability' : IDL.Float64,
    'volumeSpike' : IDL.Bool,
    'patternFormation' : IDL.Bool,
    'signalStrength' : IDL.Text,
    'projectedReversal' : IDL.Bool,
    'timingEstimate' : IDL.Float64,
    'isEarlyConfirmed' : IDL.Bool,
    'rsiMomentum' : IDL.Bool,
    'institutionalVolume' : IDL.Bool,
    'confluenceLabel' : IDL.Text,
    'confluenceScore' : IDL.Float64,
    'shortIntervalSignal' : IDL.Bool,
  });
  const CryptoAsset = IDL.Record({
    'region' : Region,
    'openInterestMomentum' : OpenInterestMomentum,
    'volatility' : IDL.Float64,
    'institutionalCriteria' : InstitutionalCriteria,
    'volumeStrength' : VolumeStrength,
    'volumeMarketCapRatio' : IDL.Float64,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'percentageChange' : IDL.Float64,
    'correlation' : IDL.Float64,
    'description' : IDL.Text,
    'volume' : IDL.Float64,
    'openInterest' : IDL.Float64,
    'momentum' : IDL.Float64,
    'isInstitutionalSetup' : IDL.Bool,
    'openInterestStatus' : IDL.Text,
    'hasStrongConfluence' : IDL.Bool,
    'confluenceScore' : IDL.Float64,
    'price' : IDL.Float64,
    'rsiTrend' : RsiTrend,
    'hasConfluence' : IDL.Bool,
    'rsiValue' : IDL.Float64,
    'recommendationScore' : IDL.Float64,
    'rsiStatus' : IDL.Text,
    'symbol' : IDL.Text,
    'setupNarrative' : IDL.Text,
    'earlyConfluence' : EarlyConfluence,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Opt(IDL.Text),
  });
  const FlowMetrics = IDL.Record({
    'direction' : IDL.Text,
    'volumeStrength' : IDL.Float64,
    'threshold' : IDL.Text,
    'netFlow' : IDL.Float64,
    'percentageChange' : IDL.Float64,
    'totalFlow' : IDL.Float64,
    'inflow' : IDL.Float64,
    'hasStrongConfluence' : IDL.Bool,
    'outflow' : IDL.Float64,
    'intensity' : IDL.Text,
  });
  const Category = IDL.Variant({
    'btc' : IDL.Null,
    'eth' : IDL.Null,
    'altcoins' : IDL.Null,
  });
  const CategoryMetrics = IDL.Record({
    'trend' : IDL.Text,
    'marketCap' : IDL.Float64,
    'name' : IDL.Text,
    'volume' : IDL.Float64,
    'flowMetrics' : FlowMetrics,
    'category' : Category,
    'price' : IDL.Float64,
  });
  const Chapter = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'number' : IDL.Nat,
  });
  const DominanceTrend = IDL.Variant({
    'up' : IDL.Null,
    'steady' : IDL.Null,
    'down' : IDL.Null,
  });
  const DominanceData = IDL.Record({
    'btcDominance' : IDL.Float64,
    'trend' : DominanceTrend,
    'change24h' : IDL.Float64,
    'usdDominance' : IDL.Float64,
    'bitcoinCap' : IDL.Float64,
    'stablecoinCap' : IDL.Float64,
    'totalCryptoCap' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const PaymentMethod = IDL.Variant({
    'icp' : IDL.Null,
    'stripe' : IDL.Null,
    'stablecoin' : IDL.Null,
  });
  const PaymentConfig = IDL.Record({
    'method' : PaymentMethod,
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
    'priceUsd' : IDL.Float64,
    'planType' : PlanType,
  });
  const PaymentTransaction = IDL.Record({
    'status' : IDL.Text,
    'method' : PaymentMethod,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'updatedAt' : IDL.Opt(IDL.Int),
    'amountUsd' : IDL.Float64,
    'planType' : PlanType,
    'transactionId' : IDL.Text,
  });
  const StripeConfigurationPublic = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'isConfigured' : IDL.Bool,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const SubscriptionStatus = IDL.Variant({
    'active' : IDL.Record({ 'expiresAt' : IDL.Opt(IDL.Int) }),
    'canceled' : IDL.Record({ 'canceledAt' : IDL.Opt(IDL.Int) }),
    'expired' : IDL.Record({ 'lastActive' : IDL.Opt(IDL.Int) }),
    'pending' : IDL.Record({ 'startedAt' : IDL.Opt(IDL.Int) }),
  });
  const Subscription = IDL.Record({
    'status' : SubscriptionStatus,
    'createdAt' : IDL.Int,
    'user' : IDL.Principal,
    'updatedAt' : IDL.Opt(IDL.Int),
    'lastPaymentId' : IDL.Opt(IDL.Text),
    'planType' : PlanType,
  });
  const TelegramPostLog = IDL.Record({
    'admin' : IDL.Principal,
    'messagePreview' : IDL.Text,
    'errorDetails' : IDL.Opt(IDL.Text),
    'httpStatusCode' : IDL.Opt(IDL.Nat),
    'timestamp' : IDL.Int,
    'success' : IDL.Bool,
  });
  const TelegramPostResult = IDL.Record({
    'resultMessage' : IDL.Text,
    'messageId' : IDL.Opt(IDL.Int),
    'errorDetails' : IDL.Opt(IDL.Text),
    'httpStatusCode' : IDL.Opt(IDL.Nat),
    'isSuccess' : IDL.Bool,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'activateSubscription' : IDL.Func([PlanType, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelSubscription' : IDL.Func([], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createIcpPayment' : IDL.Func([PlanType], [IDL.Text], []),
    'createStablecoinPayment' : IDL.Func([PlanType], [IDL.Text], []),
    'getAdminAuditLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AdminAuditEntry)],
        ['query'],
      ),
    'getAssetAnalysis' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(CryptoAsset)],
        ['query'],
      ),
    'getAssetChartData' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Float64)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryMetrics' : IDL.Func([], [IDL.Vec(CategoryMetrics)], ['query']),
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
    'getDominanceAlerts' : IDL.Func(
        [IDL.Float64],
        [
          IDL.Vec(
            IDL.Record({
              'dominanceValue' : IDL.Float64,
              'message' : IDL.Text,
              'dominanceType' : IDL.Text,
              'timestamp' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getDominanceComparison' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'btcDominance' : IDL.Float64,
              'usdDominance' : IDL.Float64,
              'dominanceRatio' : IDL.Float64,
              'relativeStrength' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getDominanceData' : IDL.Func([], [IDL.Vec(DominanceData)], ['query']),
    'getIntelligentRecommendations' : IDL.Func(
        [],
        [IDL.Vec(CryptoAsset)],
        ['query'],
      ),
    'getLatestDominanceMetrics' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'btcDominance' : IDL.Float64,
              'usdDominance' : IDL.Float64,
              'bitcoinCap' : IDL.Float64,
              'stablecoinCap' : IDL.Float64,
              'totalCryptoCap' : IDL.Float64,
              'timestamp' : IDL.Int,
            })
          ),
        ],
        ['query'],
      ),
    'getPaymentConfiguration' : IDL.Func(
        [PaymentMethod, PlanType],
        [IDL.Opt(PaymentConfig)],
        ['query'],
      ),
    'getPaymentTransaction' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PaymentTransaction)],
        ['query'],
      ),
    'getStripeConfiguration' : IDL.Func(
        [],
        [StripeConfigurationPublic],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getTelegramPostLog' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TelegramPostLog)],
        ['query'],
      ),
    'getThreeMinuteTimeframe' : IDL.Func([], [IDL.Text], ['query']),
    'getTopCapitalFlowProportionalToMarketCap' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Vec(
            IDL.Record({
              'usdInflow' : IDL.Float64,
              'marketCap' : IDL.Float64,
              'proportionalFlow' : IDL.Float64,
              'symbol' : IDL.Text,
            })
          ),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSubscription' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Subscription)],
        ['query'],
      ),
    'hasPremiumAccess' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'listAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'listChapters' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'title' : IDL.Text, 'number' : IDL.Nat }))],
        ['query'],
      ),
    'listPaymentConfigurations' : IDL.Func(
        [],
        [IDL.Vec(PaymentConfig)],
        ['query'],
      ),
    'listPaymentTransactions' : IDL.Func(
        [],
        [IDL.Vec(PaymentTransaction)],
        ['query'],
      ),
    'ping' : IDL.Func([], [IDL.Text], []),
    'recordPaymentTransaction' : IDL.Func([PaymentTransaction], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByKeyword' : IDL.Func([IDL.Text], [IDL.Vec(Chapter)], ['query']),
    'sendTelegramPost' : IDL.Func([IDL.Text], [TelegramPostResult], []),
    'setPaymentConfiguration' : IDL.Func([PaymentConfig], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateSubscription' : IDL.Func([Subscription], [], []),
  });
};

export const init = ({ IDL }) => { return []; };