/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAuditEntry {
  'action' : string,
  'admin' : Principal,
  'timestamp' : bigint,
  'details' : string,
}
export type Category = { 'btc' : null } |
  { 'eth' : null } |
  { 'altcoins' : null };
export interface CategoryMetrics {
  'trend' : string,
  'marketCap' : number,
  'name' : string,
  'volume' : number,
  'flowMetrics' : FlowMetrics,
  'category' : Category,
  'price' : number,
}
export interface Chapter {
  'title' : string,
  'content' : string,
  'number' : bigint,
}
export interface CryptoAsset {
  'region' : Region,
  'openInterestMomentum' : OpenInterestMomentum,
  'volatility' : number,
  'institutionalCriteria' : InstitutionalCriteria,
  'volumeStrength' : VolumeStrength,
  'volumeMarketCapRatio' : number,
  'marketCap' : number,
  'name' : string,
  'percentageChange' : number,
  'correlation' : number,
  'description' : string,
  'volume' : number,
  'openInterest' : number,
  'momentum' : number,
  'isInstitutionalSetup' : boolean,
  'openInterestStatus' : string,
  'hasStrongConfluence' : boolean,
  'confluenceScore' : number,
  'price' : number,
  'rsiTrend' : RsiTrend,
  'hasConfluence' : boolean,
  'rsiValue' : number,
  'recommendationScore' : number,
  'rsiStatus' : string,
  'symbol' : string,
  'setupNarrative' : string,
  'earlyConfluence' : EarlyConfluence,
}
export interface DominanceData {
  'btcDominance' : number,
  'trend' : DominanceTrend,
  'change24h' : number,
  'usdDominance' : number,
  'bitcoinCap' : number,
  'stablecoinCap' : number,
  'totalCryptoCap' : number,
  'timestamp' : bigint,
}
export type DominanceTrend = { 'up' : null } |
  { 'steady' : null } |
  { 'down' : null };
export interface EarlyConfluence {
  'probability' : number,
  'volumeSpike' : boolean,
  'patternFormation' : boolean,
  'signalStrength' : string,
  'projectedReversal' : boolean,
  'timingEstimate' : number,
  'isEarlyConfirmed' : boolean,
  'rsiMomentum' : boolean,
  'institutionalVolume' : boolean,
  'confluenceLabel' : string,
  'confluenceScore' : number,
  'shortIntervalSignal' : boolean,
}
export interface FlowMetrics {
  'direction' : string,
  'volumeStrength' : number,
  'threshold' : string,
  'netFlow' : number,
  'percentageChange' : number,
  'totalFlow' : number,
  'inflow' : number,
  'hasStrongConfluence' : boolean,
  'outflow' : number,
  'intensity' : string,
}
export interface InstitutionalCriteria {
  'hasOb' : boolean,
  'hasDisplacement' : boolean,
  'hasFvg' : boolean,
  'hasManipulation' : boolean,
  'hasInstitutionalTarget' : boolean,
  'hasMitigation' : boolean,
  'hasChoch' : boolean,
  'hasLiquidity' : boolean,
}
export type OpenInterestMomentum = { 'steady' : null } |
  { 'decreasing' : null } |
  { 'increasing' : null };
export interface PaymentConfig {
  'method' : PaymentMethod,
  'description' : string,
  'enabled' : boolean,
  'priceUsd' : number,
  'planType' : PlanType,
}
export type PaymentMethod = { 'icp' : null } |
  { 'stripe' : null } |
  { 'stablecoin' : null };
export interface PaymentTransaction {
  'status' : string,
  'method' : PaymentMethod,
  'createdAt' : bigint,
  'user' : Principal,
  'updatedAt' : [] | [bigint],
  'amountUsd' : number,
  'planType' : PlanType,
  'transactionId' : string,
}
export type PlanType = { 'lifetime' : null } |
  { 'weekly' : null };
export type Region = { 'usa' : null } |
  { 'europe' : null } |
  { 'brasil' : null } |
  { 'other' : null } |
  { 'asia' : null } |
  { 'arabia' : null } |
  { 'india' : null } |
  { 'africa' : null };
export type RsiTrend = { 'steady' : null } |
  { 'rising' : null } |
  { 'falling' : null };
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export interface StripeConfigurationPublic {
  'allowedCountries' : Array<string>,
  'isConfigured' : boolean,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Subscription {
  'status' : SubscriptionStatus,
  'createdAt' : bigint,
  'user' : Principal,
  'updatedAt' : [] | [bigint],
  'lastPaymentId' : [] | [string],
  'planType' : PlanType,
}
export type SubscriptionStatus = {
    'active' : { 'expiresAt' : [] | [bigint] }
  } |
  { 'canceled' : { 'canceledAt' : [] | [bigint] } } |
  { 'expired' : { 'lastActive' : [] | [bigint] } } |
  { 'pending' : { 'startedAt' : [] | [bigint] } };
export interface TelegramPostLog {
  'admin' : Principal,
  'messagePreview' : string,
  'errorDetails' : [] | [string],
  'httpStatusCode' : [] | [bigint],
  'timestamp' : bigint,
  'success' : boolean,
}
export interface TelegramPostResult {
  'resultMessage' : string,
  'messageId' : [] | [bigint],
  'errorDetails' : [] | [string],
  'httpStatusCode' : [] | [bigint],
  'isSuccess' : boolean,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'createdAt' : bigint,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VolumeStrength = { 'low' : null } |
  { 'veryHigh' : null } |
  { 'high' : null } |
  { 'extreme' : null } |
  { 'medium' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'activateSubscription' : ActorMethod<[PlanType, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelSubscription' : ActorMethod<[], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createIcpPayment' : ActorMethod<[PlanType], string>,
  'createStablecoinPayment' : ActorMethod<[PlanType], string>,
  'getAdminAuditLog' : ActorMethod<[bigint], Array<AdminAuditEntry>>,
  'getAssetAnalysis' : ActorMethod<[string], [] | [CryptoAsset]>,
  'getAssetChartData' : ActorMethod<[string, string], Array<number>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryMetrics' : ActorMethod<[], Array<CategoryMetrics>>,
  'getChapter' : ActorMethod<[bigint], [] | [Chapter]>,
  'getDominanceAlerts' : ActorMethod<
    [number],
    Array<
      {
        'dominanceValue' : number,
        'message' : string,
        'dominanceType' : string,
        'timestamp' : bigint,
      }
    >
  >,
  'getDominanceComparison' : ActorMethod<
    [],
    [] | [
      {
        'btcDominance' : number,
        'usdDominance' : number,
        'dominanceRatio' : number,
        'relativeStrength' : string,
      }
    ]
  >,
  'getDominanceData' : ActorMethod<[], Array<DominanceData>>,
  'getIntelligentRecommendations' : ActorMethod<[], Array<CryptoAsset>>,
  'getLatestDominanceMetrics' : ActorMethod<
    [],
    [] | [
      {
        'btcDominance' : number,
        'usdDominance' : number,
        'bitcoinCap' : number,
        'stablecoinCap' : number,
        'totalCryptoCap' : number,
        'timestamp' : bigint,
      }
    ]
  >,
  'getPaymentConfiguration' : ActorMethod<
    [PaymentMethod, PlanType],
    [] | [PaymentConfig]
  >,
  'getPaymentTransaction' : ActorMethod<[string], [] | [PaymentTransaction]>,
  'getStripeConfiguration' : ActorMethod<[], StripeConfigurationPublic>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getTelegramPostLog' : ActorMethod<[bigint], Array<TelegramPostLog>>,
  'getThreeMinuteTimeframe' : ActorMethod<[], string>,
  'getTopCapitalFlowProportionalToMarketCap' : ActorMethod<
    [bigint],
    Array<
      {
        'usdInflow' : number,
        'marketCap' : number,
        'proportionalFlow' : number,
        'symbol' : string,
      }
    >
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserSubscription' : ActorMethod<[Principal], [] | [Subscription]>,
  'hasPremiumAccess' : ActorMethod<[Principal], boolean>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'listAllUserProfiles' : ActorMethod<[], Array<UserProfile>>,
  'listChapters' : ActorMethod<
    [],
    Array<{ 'title' : string, 'number' : bigint }>
  >,
  'listPaymentConfigurations' : ActorMethod<[], Array<PaymentConfig>>,
  'listPaymentTransactions' : ActorMethod<[], Array<PaymentTransaction>>,
  'ping' : ActorMethod<[], string>,
  'recordPaymentTransaction' : ActorMethod<[PaymentTransaction], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchByKeyword' : ActorMethod<[string], Array<Chapter>>,
  'sendTelegramPost' : ActorMethod<[string], TelegramPostResult>,
  'setPaymentConfiguration' : ActorMethod<[PaymentConfig], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateSubscription' : ActorMethod<[Subscription], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];