/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface StripeConfigurationPublic {
    allowedCountries: Array<string>;
    isConfigured: boolean;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface PaymentTransaction {
    status: string;
    method: PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt?: bigint;
    amountUsd: number;
    planType: PlanType;
    transactionId: string;
}
export interface Chapter {
    title: string;
    content: string;
    number: bigint;
}
export interface Subscription {
    status: SubscriptionStatus;
    createdAt: bigint;
    user: Principal;
    updatedAt?: bigint;
    lastPaymentId?: string;
    planType: PlanType;
}
export interface CategoryMetrics {
    trend: string;
    marketCap: number;
    name: string;
    volume: number;
    flowMetrics: FlowMetrics;
    category: Category;
    price: number;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DominanceData {
    btcDominance: number;
    trend: DominanceTrend;
    change24h: number;
    usdDominance: number;
    bitcoinCap: number;
    stablecoinCap: number;
    totalCryptoCap: number;
    timestamp: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type SubscriptionStatus = {
    __kind__: "active";
    active: {
        expiresAt?: bigint;
    };
} | {
    __kind__: "canceled";
    canceled: {
        canceledAt?: bigint;
    };
} | {
    __kind__: "expired";
    expired: {
        lastActive?: bigint;
    };
} | {
    __kind__: "pending";
    pending: {
        startedAt?: bigint;
    };
};
export interface PaymentConfig {
    method: PaymentMethod;
    description: string;
    enabled: boolean;
    priceUsd: number;
    planType: PlanType;
}
export interface AdminAuditEntry {
    action: string;
    admin: Principal;
    timestamp: bigint;
    details: string;
}
export interface TelegramPostLog {
    admin: Principal;
    messagePreview: string;
    errorDetails?: string;
    httpStatusCode?: bigint;
    timestamp: bigint;
    success: boolean;
}
export interface FlowMetrics {
    direction: string;
    volumeStrength: number;
    threshold: string;
    netFlow: number;
    percentageChange: number;
    totalFlow: number;
    inflow: number;
    hasStrongConfluence: boolean;
    outflow: number;
    intensity: string;
}
export interface CryptoAsset {
    region: Region;
    openInterestMomentum: OpenInterestMomentum;
    volatility: number;
    institutionalCriteria: InstitutionalCriteria;
    volumeStrength: VolumeStrength;
    volumeMarketCapRatio: number;
    marketCap: number;
    name: string;
    percentageChange: number;
    correlation: number;
    description: string;
    volume: number;
    openInterest: number;
    momentum: number;
    isInstitutionalSetup: boolean;
    openInterestStatus: string;
    hasStrongConfluence: boolean;
    confluenceScore: number;
    price: number;
    rsiTrend: RsiTrend;
    hasConfluence: boolean;
    rsiValue: number;
    recommendationScore: number;
    rsiStatus: string;
    symbol: string;
    setupNarrative: string;
    earlyConfluence: EarlyConfluence;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface EarlyConfluence {
    probability: number;
    volumeSpike: boolean;
    patternFormation: boolean;
    signalStrength: string;
    projectedReversal: boolean;
    timingEstimate: number;
    isEarlyConfirmed: boolean;
    rsiMomentum: boolean;
    institutionalVolume: boolean;
    confluenceLabel: string;
    confluenceScore: number;
    shortIntervalSignal: boolean;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface TelegramPostResult {
    resultMessage: string;
    messageId?: bigint;
    errorDetails?: string;
    httpStatusCode?: bigint;
    isSuccess: boolean;
}
export interface InstitutionalCriteria {
    hasOb: boolean;
    hasDisplacement: boolean;
    hasFvg: boolean;
    hasManipulation: boolean;
    hasInstitutionalTarget: boolean;
    hasMitigation: boolean;
    hasChoch: boolean;
    hasLiquidity: boolean;
}
export interface UserProfile {
    name: string;
    createdAt: bigint;
    email?: string;
}
export enum Category {
    btc = "btc",
    eth = "eth",
    altcoins = "altcoins"
}
export enum DominanceTrend {
    up = "up",
    steady = "steady",
    down = "down"
}
export enum OpenInterestMomentum {
    steady = "steady",
    decreasing = "decreasing",
    increasing = "increasing"
}
export enum PaymentMethod {
    icp = "icp",
    stripe = "stripe",
    stablecoin = "stablecoin"
}
export enum PlanType {
    lifetime = "lifetime",
    weekly = "weekly"
}
export enum Region {
    usa = "usa",
    europe = "europe",
    brasil = "brasil",
    other = "other",
    asia = "asia",
    arabia = "arabia",
    india = "india",
    africa = "africa"
}
export enum RsiTrend {
    steady = "steady",
    rising = "rising",
    falling = "falling"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VolumeStrength {
    low = "low",
    veryHigh = "veryHigh",
    high = "high",
    extreme = "extreme",
    medium = "medium"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    activateSubscription(planType: PlanType, paymentId: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelSubscription(): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createIcpPayment(planType: PlanType): Promise<string>;
    createStablecoinPayment(planType: PlanType): Promise<string>;
    getAdminAuditLog(limit: bigint): Promise<Array<AdminAuditEntry>>;
    getAssetAnalysis(_symbol: string): Promise<CryptoAsset | null>;
    getAssetChartData(_symbol: string, _interval: string): Promise<Array<number>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCategoryMetrics(): Promise<Array<CategoryMetrics>>;
    getChapter(number: bigint): Promise<Chapter | null>;
    getDominanceAlerts(_threshold: number): Promise<Array<{
        dominanceValue: number;
        message: string;
        dominanceType: string;
        timestamp: bigint;
    }>>;
    getDominanceComparison(): Promise<{
        btcDominance: number;
        usdDominance: number;
        dominanceRatio: number;
        relativeStrength: string;
    } | null>;
    getDominanceData(): Promise<Array<DominanceData>>;
    getIntelligentRecommendations(): Promise<Array<CryptoAsset>>;
    getLatestDominanceMetrics(): Promise<{
        btcDominance: number;
        usdDominance: number;
        bitcoinCap: number;
        stablecoinCap: number;
        totalCryptoCap: number;
        timestamp: bigint;
    } | null>;
    getPaymentConfiguration(method: PaymentMethod, planType: PlanType): Promise<PaymentConfig | null>;
    getPaymentTransaction(transactionId: string): Promise<PaymentTransaction | null>;
    getStripeConfiguration(): Promise<StripeConfigurationPublic>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getSubscription(): Promise<Subscription | null>;
    getTelegramPostLog(limit: bigint): Promise<Array<TelegramPostLog>>;
    getThreeMinuteTimeframe(): Promise<string>;
    getTopCapitalFlowProportionalToMarketCap(_limit: bigint): Promise<Array<{
        usdInflow: number;
        marketCap: number;
        proportionalFlow: number;
        symbol: string;
    }>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserSubscription(user: Principal): Promise<Subscription | null>;
    hasPremiumAccess(user: Principal): Promise<boolean>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAllSubscriptions(): Promise<Array<Subscription>>;
    listAllUserProfiles(): Promise<Array<UserProfile>>;
    listChapters(): Promise<Array<{
        title: string;
        number: bigint;
    }>>;
    listPaymentConfigurations(): Promise<Array<PaymentConfig>>;
    listPaymentTransactions(): Promise<Array<PaymentTransaction>>;
    ping(): Promise<string>;
    recordPaymentTransaction(transaction: PaymentTransaction): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchByKeyword(keyword: string): Promise<Array<Chapter>>;
    sendTelegramPost(message: string): Promise<TelegramPostResult>;
    setPaymentConfiguration(config: PaymentConfig): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateSubscription(subscription: Subscription): Promise<void>;
}
import type { Category as _Category, CategoryMetrics as _CategoryMetrics, Chapter as _Chapter, CryptoAsset as _CryptoAsset, DominanceData as _DominanceData, DominanceTrend as _DominanceTrend, EarlyConfluence as _EarlyConfluence, FlowMetrics as _FlowMetrics, InstitutionalCriteria as _InstitutionalCriteria, OpenInterestMomentum as _OpenInterestMomentum, PaymentConfig as _PaymentConfig, PaymentMethod as _PaymentMethod, PaymentTransaction as _PaymentTransaction, PlanType as _PlanType, Region as _Region, RsiTrend as _RsiTrend, StripeSessionStatus as _StripeSessionStatus, Subscription as _Subscription, SubscriptionStatus as _SubscriptionStatus, TelegramPostLog as _TelegramPostLog, TelegramPostResult as _TelegramPostResult, UserProfile as _UserProfile, UserRole as _UserRole, VolumeStrength as _VolumeStrength, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async activateSubscription(arg0: PlanType, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activateSubscription(to_candid_PlanType_n8(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activateSubscription(to_candid_PlanType_n8(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelSubscription(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelSubscription();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelSubscription();
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createIcpPayment(arg0: PlanType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createIcpPayment(to_candid_PlanType_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createIcpPayment(to_candid_PlanType_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createStablecoinPayment(arg0: PlanType): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createStablecoinPayment(to_candid_PlanType_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStablecoinPayment(to_candid_PlanType_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAdminAuditLog(arg0: bigint): Promise<Array<AdminAuditEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAuditLog(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAuditLog(arg0);
            return result;
        }
    }
    async getAssetAnalysis(arg0: string): Promise<CryptoAsset | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetAnalysis(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetAnalysis(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAssetChartData(arg0: string, arg1: string): Promise<Array<number>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAssetChartData(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAssetChartData(arg0, arg1);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategoryMetrics(): Promise<Array<CategoryMetrics>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategoryMetrics();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategoryMetrics();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChapter(arg0: bigint): Promise<Chapter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDominanceAlerts(arg0: number): Promise<Array<{
        dominanceValue: number;
        message: string;
        dominanceType: string;
        timestamp: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDominanceAlerts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDominanceAlerts(arg0);
            return result;
        }
    }
    async getDominanceComparison(): Promise<{
        btcDominance: number;
        usdDominance: number;
        dominanceRatio: number;
        relativeStrength: string;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDominanceComparison();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDominanceComparison();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDominanceData(): Promise<Array<DominanceData>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDominanceData();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDominanceData();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIntelligentRecommendations(): Promise<Array<CryptoAsset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getIntelligentRecommendations();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIntelligentRecommendations();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestDominanceMetrics(): Promise<{
        btcDominance: number;
        usdDominance: number;
        bitcoinCap: number;
        stablecoinCap: number;
        totalCryptoCap: number;
        timestamp: bigint;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestDominanceMetrics();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestDominanceMetrics();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentConfiguration(arg0: PaymentMethod, arg1: PlanType): Promise<PaymentConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentConfiguration(to_candid_PaymentMethod_n43(this._uploadFile, this._downloadFile, arg0), to_candid_PlanType_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentConfiguration(to_candid_PaymentMethod_n43(this._uploadFile, this._downloadFile, arg0), to_candid_PlanType_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentTransaction(arg0: string): Promise<PaymentTransaction | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentTransaction(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentTransaction(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeConfiguration(): Promise<StripeConfigurationPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeConfiguration();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeConfiguration();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSubscription(): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscription();
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscription();
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTelegramPostLog(arg0: bigint): Promise<Array<TelegramPostLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTelegramPostLog(arg0);
                return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTelegramPostLog(arg0);
            return from_candid_vec_n68(this._uploadFile, this._downloadFile, result);
        }
    }
    async getThreeMinuteTimeframe(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getThreeMinuteTimeframe();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getThreeMinuteTimeframe();
            return result;
        }
    }
    async getTopCapitalFlowProportionalToMarketCap(arg0: bigint): Promise<Array<{
        usdInflow: number;
        marketCap: number;
        proportionalFlow: number;
        symbol: string;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopCapitalFlowProportionalToMarketCap(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopCapitalFlowProportionalToMarketCap(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserSubscription(arg0: Principal): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserSubscription(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserSubscription(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasPremiumAccess(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPremiumAccess(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPremiumAccess(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllSubscriptions();
                return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllSubscriptions();
            return from_candid_vec_n71(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAllUserProfiles(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUserProfiles();
                return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUserProfiles();
            return from_candid_vec_n72(this._uploadFile, this._downloadFile, result);
        }
    }
    async listChapters(): Promise<Array<{
        title: string;
        number: bigint;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChapters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChapters();
            return result;
        }
    }
    async listPaymentConfigurations(): Promise<Array<PaymentConfig>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPaymentConfigurations();
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPaymentConfigurations();
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPaymentTransactions(): Promise<Array<PaymentTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPaymentTransactions();
                return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPaymentTransactions();
            return from_candid_vec_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async ping(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.ping();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ping();
            return result;
        }
    }
    async recordPaymentTransaction(arg0: PaymentTransaction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPaymentTransaction(to_candid_PaymentTransaction_n75(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPaymentTransaction(to_candid_PaymentTransaction_n75(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n77(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n77(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchByKeyword(arg0: string): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByKeyword(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByKeyword(arg0);
            return result;
        }
    }
    async sendTelegramPost(arg0: string): Promise<TelegramPostResult> {
        if (this.processError) {
            try {
                const result = await this.actor.sendTelegramPost(arg0);
                return from_candid_TelegramPostResult_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendTelegramPost(arg0);
            return from_candid_TelegramPostResult_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async setPaymentConfiguration(arg0: PaymentConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentConfiguration(to_candid_PaymentConfig_n81(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentConfiguration(to_candid_PaymentConfig_n81(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateSubscription(arg0: Subscription): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscription(to_candid_Subscription_n83(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscription(to_candid_Subscription_n83(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_CategoryMetrics_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryMetrics): CategoryMetrics {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_CryptoAsset_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CryptoAsset): CryptoAsset {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DominanceData_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DominanceData): DominanceData {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_DominanceTrend_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DominanceTrend): DominanceTrend {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_OpenInterestMomentum_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OpenInterestMomentum): OpenInterestMomentum {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentConfig_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentConfig): PaymentConfig {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentTransaction_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentTransaction): PaymentTransaction {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_PlanType_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlanType): PlanType {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Region_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Region): Region {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_RsiTrend_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RsiTrend): RsiTrend {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
function from_candid_SubscriptionStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionStatus): SubscriptionStatus {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
function from_candid_TelegramPostLog_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TelegramPostLog): TelegramPostLog {
    return from_candid_record_n70(_uploadFile, _downloadFile, value);
}
function from_candid_TelegramPostResult_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TelegramPostResult): TelegramPostResult {
    return from_candid_record_n80(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_VolumeStrength_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VolumeStrength): VolumeStrength {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CryptoAsset]): CryptoAsset | null {
    return value.length === 0 ? null : from_candid_CryptoAsset_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chapter]): Chapter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        btcDominance: number;
        usdDominance: number;
        dominanceRatio: number;
        relativeStrength: string;
    }]): {
    btcDominance: number;
    usdDominance: number;
    dominanceRatio: number;
    relativeStrength: string;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        btcDominance: number;
        usdDominance: number;
        bitcoinCap: number;
        stablecoinCap: number;
        totalCryptoCap: number;
        timestamp: bigint;
    }]): {
    btcDominance: number;
    usdDominance: number;
    bitcoinCap: number;
    stablecoinCap: number;
    totalCryptoCap: number;
    timestamp: bigint;
} | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentConfig]): PaymentConfig | null {
    return value.length === 0 ? null : from_candid_PaymentConfig_n46(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentTransaction]): PaymentTransaction | null {
    return value.length === 0 ? null : from_candid_PaymentTransaction_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n60(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    region: _Region;
    openInterestMomentum: _OpenInterestMomentum;
    volatility: number;
    institutionalCriteria: _InstitutionalCriteria;
    volumeStrength: _VolumeStrength;
    volumeMarketCapRatio: number;
    marketCap: number;
    name: string;
    percentageChange: number;
    correlation: number;
    description: string;
    volume: number;
    openInterest: number;
    momentum: number;
    isInstitutionalSetup: boolean;
    openInterestStatus: string;
    hasStrongConfluence: boolean;
    confluenceScore: number;
    price: number;
    rsiTrend: _RsiTrend;
    hasConfluence: boolean;
    rsiValue: number;
    recommendationScore: number;
    rsiStatus: string;
    symbol: string;
    setupNarrative: string;
    earlyConfluence: _EarlyConfluence;
}): {
    region: Region;
    openInterestMomentum: OpenInterestMomentum;
    volatility: number;
    institutionalCriteria: InstitutionalCriteria;
    volumeStrength: VolumeStrength;
    volumeMarketCapRatio: number;
    marketCap: number;
    name: string;
    percentageChange: number;
    correlation: number;
    description: string;
    volume: number;
    openInterest: number;
    momentum: number;
    isInstitutionalSetup: boolean;
    openInterestStatus: string;
    hasStrongConfluence: boolean;
    confluenceScore: number;
    price: number;
    rsiTrend: RsiTrend;
    hasConfluence: boolean;
    rsiValue: number;
    recommendationScore: number;
    rsiStatus: string;
    symbol: string;
    setupNarrative: string;
    earlyConfluence: EarlyConfluence;
} {
    return {
        region: from_candid_Region_n15(_uploadFile, _downloadFile, value.region),
        openInterestMomentum: from_candid_OpenInterestMomentum_n17(_uploadFile, _downloadFile, value.openInterestMomentum),
        volatility: value.volatility,
        institutionalCriteria: value.institutionalCriteria,
        volumeStrength: from_candid_VolumeStrength_n19(_uploadFile, _downloadFile, value.volumeStrength),
        volumeMarketCapRatio: value.volumeMarketCapRatio,
        marketCap: value.marketCap,
        name: value.name,
        percentageChange: value.percentageChange,
        correlation: value.correlation,
        description: value.description,
        volume: value.volume,
        openInterest: value.openInterest,
        momentum: value.momentum,
        isInstitutionalSetup: value.isInstitutionalSetup,
        openInterestStatus: value.openInterestStatus,
        hasStrongConfluence: value.hasStrongConfluence,
        confluenceScore: value.confluenceScore,
        price: value.price,
        rsiTrend: from_candid_RsiTrend_n21(_uploadFile, _downloadFile, value.rsiTrend),
        hasConfluence: value.hasConfluence,
        rsiValue: value.rsiValue,
        recommendationScore: value.recommendationScore,
        rsiStatus: value.rsiStatus,
        symbol: value.symbol,
        setupNarrative: value.setupNarrative,
        earlyConfluence: value.earlyConfluence
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: bigint;
    email: [] | [string];
}): {
    name: string;
    createdAt: bigint;
    email?: string;
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        email: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trend: string;
    marketCap: number;
    name: string;
    volume: number;
    flowMetrics: _FlowMetrics;
    category: _Category;
    price: number;
}): {
    trend: string;
    marketCap: number;
    name: string;
    volume: number;
    flowMetrics: FlowMetrics;
    category: Category;
    price: number;
} {
    return {
        trend: value.trend,
        marketCap: value.marketCap,
        name: value.name,
        volume: value.volume,
        flowMetrics: value.flowMetrics,
        category: from_candid_Category_n32(_uploadFile, _downloadFile, value.category),
        price: value.price
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btcDominance: number;
    trend: _DominanceTrend;
    change24h: number;
    usdDominance: number;
    bitcoinCap: number;
    stablecoinCap: number;
    totalCryptoCap: number;
    timestamp: bigint;
}): {
    btcDominance: number;
    trend: DominanceTrend;
    change24h: number;
    usdDominance: number;
    bitcoinCap: number;
    stablecoinCap: number;
    totalCryptoCap: number;
    timestamp: bigint;
} {
    return {
        btcDominance: value.btcDominance,
        trend: from_candid_DominanceTrend_n39(_uploadFile, _downloadFile, value.trend),
        change24h: value.change24h,
        usdDominance: value.usdDominance,
        bitcoinCap: value.bitcoinCap,
        stablecoinCap: value.stablecoinCap,
        totalCryptoCap: value.totalCryptoCap,
        timestamp: value.timestamp
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: _PaymentMethod;
    description: string;
    enabled: boolean;
    priceUsd: number;
    planType: _PlanType;
}): {
    method: PaymentMethod;
    description: string;
    enabled: boolean;
    priceUsd: number;
    planType: PlanType;
} {
    return {
        method: from_candid_PaymentMethod_n48(_uploadFile, _downloadFile, value.method),
        description: value.description,
        enabled: value.enabled,
        priceUsd: value.priceUsd,
        planType: from_candid_PlanType_n50(_uploadFile, _downloadFile, value.planType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    method: _PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt: [] | [bigint];
    amountUsd: number;
    planType: _PlanType;
    transactionId: string;
}): {
    status: string;
    method: PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt?: bigint;
    amountUsd: number;
    planType: PlanType;
    transactionId: string;
} {
    return {
        status: value.status,
        method: from_candid_PaymentMethod_n48(_uploadFile, _downloadFile, value.method),
        createdAt: value.createdAt,
        user: value.user,
        updatedAt: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.updatedAt)),
        amountUsd: value.amountUsd,
        planType: from_candid_PlanType_n50(_uploadFile, _downloadFile, value.planType),
        transactionId: value.transactionId
    };
}
function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _SubscriptionStatus;
    createdAt: bigint;
    user: Principal;
    updatedAt: [] | [bigint];
    lastPaymentId: [] | [string];
    planType: _PlanType;
}): {
    status: SubscriptionStatus;
    createdAt: bigint;
    user: Principal;
    updatedAt?: bigint;
    lastPaymentId?: string;
    planType: PlanType;
} {
    return {
        status: from_candid_SubscriptionStatus_n62(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        user: value.user,
        updatedAt: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.updatedAt)),
        lastPaymentId: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.lastPaymentId)),
        planType: from_candid_PlanType_n50(_uploadFile, _downloadFile, value.planType)
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt: [] | [bigint];
}): {
    expiresAt?: bigint;
} {
    return {
        expiresAt: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.expiresAt))
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canceledAt: [] | [bigint];
}): {
    canceledAt?: bigint;
} {
    return {
        canceledAt: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.canceledAt))
    };
}
function from_candid_record_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastActive: [] | [bigint];
}): {
    lastActive?: bigint;
} {
    return {
        lastActive: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.lastActive))
    };
}
function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startedAt: [] | [bigint];
}): {
    startedAt?: bigint;
} {
    return {
        startedAt: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.startedAt))
    };
}
function from_candid_record_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: Principal;
    messagePreview: string;
    errorDetails: [] | [string];
    httpStatusCode: [] | [bigint];
    timestamp: bigint;
    success: boolean;
}): {
    admin: Principal;
    messagePreview: string;
    errorDetails?: string;
    httpStatusCode?: bigint;
    timestamp: bigint;
    success: boolean;
} {
    return {
        admin: value.admin,
        messagePreview: value.messagePreview,
        errorDetails: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.errorDetails)),
        httpStatusCode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.httpStatusCode)),
        timestamp: value.timestamp,
        success: value.success
    };
}
function from_candid_record_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    resultMessage: string;
    messageId: [] | [bigint];
    errorDetails: [] | [string];
    httpStatusCode: [] | [bigint];
    isSuccess: boolean;
}): {
    resultMessage: string;
    messageId?: bigint;
    errorDetails?: string;
    httpStatusCode?: bigint;
    isSuccess: boolean;
} {
    return {
        resultMessage: value.resultMessage,
        messageId: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.messageId)),
        errorDetails: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.errorDetails)),
        httpStatusCode: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.httpStatusCode)),
        isSuccess: value.isSuccess
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    usa: null;
} | {
    europe: null;
} | {
    brasil: null;
} | {
    other: null;
} | {
    asia: null;
} | {
    arabia: null;
} | {
    india: null;
} | {
    africa: null;
}): Region {
    return "usa" in value ? Region.usa : "europe" in value ? Region.europe : "brasil" in value ? Region.brasil : "other" in value ? Region.other : "asia" in value ? Region.asia : "arabia" in value ? Region.arabia : "india" in value ? Region.india : "africa" in value ? Region.africa : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    steady: null;
} | {
    decreasing: null;
} | {
    increasing: null;
}): OpenInterestMomentum {
    return "steady" in value ? OpenInterestMomentum.steady : "decreasing" in value ? OpenInterestMomentum.decreasing : "increasing" in value ? OpenInterestMomentum.increasing : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    veryHigh: null;
} | {
    high: null;
} | {
    extreme: null;
} | {
    medium: null;
}): VolumeStrength {
    return "low" in value ? VolumeStrength.low : "veryHigh" in value ? VolumeStrength.veryHigh : "high" in value ? VolumeStrength.high : "extreme" in value ? VolumeStrength.extreme : "medium" in value ? VolumeStrength.medium : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    steady: null;
} | {
    rising: null;
} | {
    falling: null;
}): RsiTrend {
    return "steady" in value ? RsiTrend.steady : "rising" in value ? RsiTrend.rising : "falling" in value ? RsiTrend.falling : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    btc: null;
} | {
    eth: null;
} | {
    altcoins: null;
}): Category {
    return "btc" in value ? Category.btc : "eth" in value ? Category.eth : "altcoins" in value ? Category.altcoins : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    up: null;
} | {
    steady: null;
} | {
    down: null;
}): DominanceTrend {
    return "up" in value ? DominanceTrend.up : "steady" in value ? DominanceTrend.steady : "down" in value ? DominanceTrend.down : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    icp: null;
} | {
    stripe: null;
} | {
    stablecoin: null;
}): PaymentMethod {
    return "icp" in value ? PaymentMethod.icp : "stripe" in value ? PaymentMethod.stripe : "stablecoin" in value ? PaymentMethod.stablecoin : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lifetime: null;
} | {
    weekly: null;
}): PlanType {
    return "lifetime" in value ? PlanType.lifetime : "weekly" in value ? PlanType.weekly : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n58(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: {
        expiresAt: [] | [bigint];
    };
} | {
    canceled: {
        canceledAt: [] | [bigint];
    };
} | {
    expired: {
        lastActive: [] | [bigint];
    };
} | {
    pending: {
        startedAt: [] | [bigint];
    };
}): {
    __kind__: "active";
    active: {
        expiresAt?: bigint;
    };
} | {
    __kind__: "canceled";
    canceled: {
        canceledAt?: bigint;
    };
} | {
    __kind__: "expired";
    expired: {
        lastActive?: bigint;
    };
} | {
    __kind__: "pending";
    pending: {
        startedAt?: bigint;
    };
} {
    return "active" in value ? {
        __kind__: "active",
        active: from_candid_record_n64(_uploadFile, _downloadFile, value.active)
    } : "canceled" in value ? {
        __kind__: "canceled",
        canceled: from_candid_record_n65(_uploadFile, _downloadFile, value.canceled)
    } : "expired" in value ? {
        __kind__: "expired",
        expired: from_candid_record_n66(_uploadFile, _downloadFile, value.expired)
    } : "pending" in value ? {
        __kind__: "pending",
        pending: from_candid_record_n67(_uploadFile, _downloadFile, value.pending)
    } : value;
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CategoryMetrics>): Array<CategoryMetrics> {
    return value.map((x)=>from_candid_CategoryMetrics_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DominanceData>): Array<DominanceData> {
    return value.map((x)=>from_candid_DominanceData_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CryptoAsset>): Array<CryptoAsset> {
    return value.map((x)=>from_candid_CryptoAsset_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TelegramPostLog>): Array<TelegramPostLog> {
    return value.map((x)=>from_candid_TelegramPostLog_n69(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n60(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentConfig>): Array<PaymentConfig> {
    return value.map((x)=>from_candid_PaymentConfig_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PaymentTransaction>): Array<PaymentTransaction> {
    return value.map((x)=>from_candid_PaymentTransaction_n53(_uploadFile, _downloadFile, x));
}
function to_candid_PaymentConfig_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentConfig): _PaymentConfig {
    return to_candid_record_n82(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentTransaction_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentTransaction): _PaymentTransaction {
    return to_candid_record_n76(_uploadFile, _downloadFile, value);
}
function to_candid_PlanType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): _PlanType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SubscriptionStatus_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubscriptionStatus): _SubscriptionStatus {
    return to_candid_variant_n86(_uploadFile, _downloadFile, value);
}
function to_candid_Subscription_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Subscription): _Subscription {
    return to_candid_record_n84(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n78(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: string;
    method: PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt?: bigint;
    amountUsd: number;
    planType: PlanType;
    transactionId: string;
}): {
    status: string;
    method: _PaymentMethod;
    createdAt: bigint;
    user: Principal;
    updatedAt: [] | [bigint];
    amountUsd: number;
    planType: _PlanType;
    transactionId: string;
} {
    return {
        status: value.status,
        method: to_candid_PaymentMethod_n43(_uploadFile, _downloadFile, value.method),
        createdAt: value.createdAt,
        user: value.user,
        updatedAt: value.updatedAt ? candid_some(value.updatedAt) : candid_none(),
        amountUsd: value.amountUsd,
        planType: to_candid_PlanType_n8(_uploadFile, _downloadFile, value.planType),
        transactionId: value.transactionId
    };
}
function to_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    createdAt: bigint;
    email?: string;
}): {
    name: string;
    createdAt: bigint;
    email: [] | [string];
} {
    return {
        name: value.name,
        createdAt: value.createdAt,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: PaymentMethod;
    description: string;
    enabled: boolean;
    priceUsd: number;
    planType: PlanType;
}): {
    method: _PaymentMethod;
    description: string;
    enabled: boolean;
    priceUsd: number;
    planType: _PlanType;
} {
    return {
        method: to_candid_PaymentMethod_n43(_uploadFile, _downloadFile, value.method),
        description: value.description,
        enabled: value.enabled,
        priceUsd: value.priceUsd,
        planType: to_candid_PlanType_n8(_uploadFile, _downloadFile, value.planType)
    };
}
function to_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: SubscriptionStatus;
    createdAt: bigint;
    user: Principal;
    updatedAt?: bigint;
    lastPaymentId?: string;
    planType: PlanType;
}): {
    status: _SubscriptionStatus;
    createdAt: bigint;
    user: Principal;
    updatedAt: [] | [bigint];
    lastPaymentId: [] | [string];
    planType: _PlanType;
} {
    return {
        status: to_candid_SubscriptionStatus_n85(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        user: value.user,
        updatedAt: value.updatedAt ? candid_some(value.updatedAt) : candid_none(),
        lastPaymentId: value.lastPaymentId ? candid_some(value.lastPaymentId) : candid_none(),
        planType: to_candid_PlanType_n8(_uploadFile, _downloadFile, value.planType)
    };
}
function to_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    startedAt?: bigint;
}): {
    startedAt: [] | [bigint];
} {
    return {
        startedAt: value.startedAt ? candid_some(value.startedAt) : candid_none()
    };
}
function to_candid_record_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastActive?: bigint;
}): {
    lastActive: [] | [bigint];
} {
    return {
        lastActive: value.lastActive ? candid_some(value.lastActive) : candid_none()
    };
}
function to_candid_record_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    canceledAt?: bigint;
}): {
    canceledAt: [] | [bigint];
} {
    return {
        canceledAt: value.canceledAt ? candid_some(value.canceledAt) : candid_none()
    };
}
function to_candid_record_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expiresAt?: bigint;
}): {
    expiresAt: [] | [bigint];
} {
    return {
        expiresAt: value.expiresAt ? candid_some(value.expiresAt) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    icp: null;
} | {
    stripe: null;
} | {
    stablecoin: null;
} {
    return value == PaymentMethod.icp ? {
        icp: null
    } : value == PaymentMethod.stripe ? {
        stripe: null
    } : value == PaymentMethod.stablecoin ? {
        stablecoin: null
    } : value;
}
function to_candid_variant_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "active";
    active: {
        expiresAt?: bigint;
    };
} | {
    __kind__: "canceled";
    canceled: {
        canceledAt?: bigint;
    };
} | {
    __kind__: "expired";
    expired: {
        lastActive?: bigint;
    };
} | {
    __kind__: "pending";
    pending: {
        startedAt?: bigint;
    };
}): {
    active: {
        expiresAt: [] | [bigint];
    };
} | {
    canceled: {
        canceledAt: [] | [bigint];
    };
} | {
    expired: {
        lastActive: [] | [bigint];
    };
} | {
    pending: {
        startedAt: [] | [bigint];
    };
} {
    return value.__kind__ === "active" ? {
        active: to_candid_record_n90(_uploadFile, _downloadFile, value.active)
    } : value.__kind__ === "canceled" ? {
        canceled: to_candid_record_n89(_uploadFile, _downloadFile, value.canceled)
    } : value.__kind__ === "expired" ? {
        expired: to_candid_record_n88(_uploadFile, _downloadFile, value.expired)
    } : value.__kind__ === "pending" ? {
        pending: to_candid_record_n87(_uploadFile, _downloadFile, value.pending)
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): {
    lifetime: null;
} | {
    weekly: null;
} {
    return value == PlanType.lifetime ? {
        lifetime: null
    } : value == PlanType.weekly ? {
        weekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
